[tool.poetry]
name = "searchgpt"
version = "0.1.0"
description = ""
authors = ["Kamil Hryniewicz <kamil.hryniewicz@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
gradio = "^3.28.3"
python = "^3.11"

[tool.poetry.group.dev.dependencies]
black = "^23.3.0"
pylint = "^2.17.4"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
